service: aws-node-http-api-project
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: eu-west-2
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:eu-west-2:218767131295:table/CrudTable  

functions:
  AddData:
    handler: src/AddData.handler
    events:
      - httpApi:
          path: /
          method: post
  FetchAll:
    handler: src/FetchAll.handler
    events:
      - httpApi:
          path: /fetchall
          method: get        
  FetchOne:
    handler: src/FetchOne.handler
    events:
      - httpApi:
          path: /fetchone/{id}
          method: get
  UpdateData:
    handler: src/UpdateData.handler
    events:
      - httpApi:
          path: /updatedata/{id}
          method: put
resources:
  Resources:
    CrudTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CrudTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH